[BE] 백엔드 리뷰요청
codesquad-member-2020/sidedish-11 pull request #58
Opened 2020-05-01 11:48 UTC by wooody92

안녕하세요, 리뷰 요청드립니다. 언제나 감사합니다!

### 학습

- 배민찬 API 기능 구현
- DTO를 사용하여 원하는 JSON 형태로 데이터 가공하기
- Jdbc Template을 사용하여 DAO 생성
- OAuth를 사용한 로그인 기능 구현

### 질문

- 처음 DTO 이용하여 데이터를 가공해보았는데, 아래처럼 리스트 타입으로 데이터를 가공해야 할 때 아래처럼 생성자에서 반복문을 사용하였습니다. 굉장히 어색하게 느껴지지만 별다른 좋은 방법이 생각나지 않는데, 어떤 방식으로 처리해야 좋을까요?

```java
public class ItemResponse {
    @JsonIgnore
    private Long id;
    private String detail_hash;

    @JsonProperty("badge")
    private List<String> badgeStrings = new ArrayList<>();

    public ItemResponse(Item item) {
        this.id = item.getId();
        this.detail_hash = item.getHash();

        for (Badge badge : item.getBadges()) {
            badgeStrings.add(badge.getName());
        }
    }
```

- DAO는 Entity와 DTO 중 어느 곳에 작성되어야 할까요? 저는 Entity에 관하여 DAO를 작성하였고 그 Entity 객체를 활용하여 DTO를 생성했습니다. DTO 클래스를 만들고 필요한 데이터를 DAO를 이용하여 맵핑시키는 게 맞는 방법일까요?

- 제가 작성한 ItemDao 클래스에서 아래와 같이 하나의 아이템을 조회하는데 관계형 테이블로 연결된 항목들을 조회하기위해 여러번 쿼리를 요청합니다. 좋은 방식이 아니라고 생각이 듭니다. JOIN을 이용하면 쿼리 수를 줄일 수 있을까요? 아니면 어떤 방법이 있을까요?

```java
private Item getItem(ResultSet rs, Long id) throws SQLException {
        Item item = new Item();
        item.setId(rs.getLong("id"));
        item.setHash(rs.getString("hash"));
        item.setImage(rs.getString("image"));
        item.setTitle(rs.getString("title"));
  
  			// 여기서 아이템 테이블과 관련된 다른 테이블 조회 요청
        item.setBadges(getBadges(id));
        item.setDeliveryTypes(getDeliveryType(id));
        item.setThumbImages(getThumbImage(id));
        item.setDetailSections(getDetailSection(id));
        item.setColors(getColor(id));
        return item;
    }

private List<Badge> getBadges(Long itemId) {
        String sql = "SELECT badge.id AS id, badge.name AS name, badge.item_key AS item_key" +
                " FROM badge" +
                " WHERE badge.item = ?" +
                " ORDER BY item_key";

        RowMapper<Badge> badgeMapper = (rs, rowNum) -> {
            Badge badge = new Badge(rs.getString("name"));
            badge.setId(rs.getLong("id"));
            return badge;
        };
        return jdbcTemplate.query(sql, new Object[] {itemId}, badgeMapper);
    }
```

2020-05-05 02:35 UTC, wheejuni requested changes
수고 많으셨습니다. 
일부 Java 기본 컨벤션이 지켜지지 않은 부분은 살짝 아쉽네요. 

개선점 코멘트로 남겨드렸으니 도움 되었으면 좋겠습니다. 
질문에 대한 답변은 별도 코멘트로 남길게요.

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/HELP.md
> +# Getting Started
기본 생성된 `README.md` 는 프로젝트와 무관하므로 빼주는 것이 보기 좋습니다.

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/common/CommonUtils.java
> +public class CommonUtils {
유틸성 클래스는 아닌 것 같아요. 
더 나은 클래스 이름을 고민해보시면 어떨까요?

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/ApiDetailController.java
> +        return ResponseEntity.ok(itemDetailResponse);
예외 처리나 기타 로직이 필요없다면, 아래와 같이 한 줄로 표현할 수도 있겠네요. 

```suggestion
        return ResponseEntity.ok(itemService.getItemDetail(hash));
```

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/ApiDetailController.java
> +        return ResponseEntity.ok(itemDetailResponse);
예외 처리나 기타 로직이 필요없다면, 아래와 같이 한 줄로 표현할 수도 있겠네요. 

```suggestion
        return ResponseEntity.ok(itemService.getItemDetail(hash));
```

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/LoginController.java
> +        response.addCookie(cookie);
JWT기반의 인증로직이라면 로그아웃은 FE의 책임이긴 해요. 
여기서 이렇게 쿠키를 만료시킨다해도 FE에 JWT가 남아있지 않으리라고 보장하기도 어렵기도 하고요. 

JWT는 한번 발급되면 만료일이 될 때까지 인위적인 만료 처리가 매우 어려운데요, 
이 문제를 해결하려면 별도의 데이터베이스 테이블 스키마를 설계해서, JWT에 대해 블랙리스트 관리를 하는게 좋긴 해요.
아래 링크를 참고해보심 좋겠어요(여기선 Node.js + Redis를 사용했네요. 기본적인 컨셉만 이해하세요).

https://dev.to/mr_cea/using-redis-for-token-blacklisting-in-node-js-42g7

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/LoginController.java
> +        response.setHeader(AUTHORIZATION, jwt);
`response` 에 `Authorization` 이라는 헤더를 내려줄 필욘 없어보입니다. 
body에 토큰을 보내도 될거같아요.

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/cors/SimpleCorsFilter.java
> +    }
테스트 목적으로 로깅을 추가해 본거라면 실제 배포시엔 지워주시고요.

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/dto/ItemDetail.java
> +    private String top_image;
애노테이션 사용시 필드와 이전 행 사이에 한 줄의 공백 만들어 주시고요. 
자바 필드명에 언더스코어 사용은 자제해 주세요.

```suggestion

@JsonIgnore
private String hash;

@JsonProperty(name = "top_image")
private String topImage;

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/dto/ItemDetail.java
> +    public ItemDetail(Item item) {
"static factory method" 학습하시고 사용 검토해주세요.

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/entity/Badge.java
> +@Getter @Setter
한 줄에 하나의 애노테이션을 선언해 주세요.

```suggestion
@Getter
@Setter
```

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/entity/Category.java
> +    }
빈 중괄호는 한 줄에 선언해 주세요. 

```suggestion
public Category() {}

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/exception/DataNotFoundException.java
> +    private final int ERROR_CODE;
static 변수가 아니므로 upper camel을 사용할 필욘 없습니다. 

```suggestion
    private final int errorCode;

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/repository/CategoryDao.java
> +        jdbcTemplate = new JdbcTemplate(dataSource);
`JdbcTemplate` 은 thread-safe하고, 여러 DAO에서 공통적으로 사용되기때문에,
별도의 `@Configuration` 클래스를 선언해서 스프링 빈으로 준비하는 것이 좋습니다. 

나중에 프로젝트가 비대해지다보면 phase별로 여러개의 `datasource` 를 사용해야 할 때도 오는데요, 
그 때도 `JdbcTemplate` 이 빈으로 관리되어야 수정하기가 좋습니다.

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/service/LoginService.java
> +    @Transactional
트랜잭션이 필요하지 않은 것 같은데요?

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/service/LoginService.java
> +    @Transactional
여기도 트랜잭션이 필요하지 않은 것 같은데요?

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/service/LoginService.java
> +    @Transactional
`@Transactional` 의 역할 다시 학습하시고 적용하시기를 권합니다.

2020-05-05 02:35 UTC, wheejuni commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/repository/ItemRepository.java
> +public interface ItemRepository extends CrudRepository<Item, Long> {
헙 이번 과제에서 이거 안 쓰기로 하지 않았나요....

2020-05-05 02:48 UTC, wheejuni commented
질문하신 사항에 대해 답변 드려요. 

> 처음 DTO 이용하여 데이터를 가공해보았는데, 아래처럼 리스트 타입으로 데이터를 가공해야 할 때 아래처럼 생성자에서 반복문을 사용하였습니다. 굉장히 어색하게 느껴지지만 별다른 좋은 방법이 생각나지 않는데, 어떤 방식으로 처리해야 좋을까요?

이 방법도 나쁘진 않지만, `stream` 을 사용하면 조금 더 나아질 것 같아요. 

`item.getBadges().stream().map(b -> ...`

> DAO는 Entity와 DTO 중 어느 곳에 작성되어야 할까요? 저는 Entity에 관하여 DAO를 작성하였고 그 Entity 객체를 활용하여 DTO를 생성했습니다. DTO 클래스를 만들고 필요한 데이터를 DAO를 이용하여 맵핑시키는 게 맞는 방법일까요?

DAO, Entity, DTO는 서로 겹치는 역할이 아니고, 서로의 역할범위가 완전히 다릅니다. 
어느 순간에도 테이블에 탑재된 정보 그 자체를 표현하는 객체는 **Entity의 역할** 이어야 하겠습니다.
그리고 DAO가 DBMS에 쿼리를 날리고 그 결과를 표현할 때도 당연히 엔티티를 사용해야 합니다. 

DTO는 프레젠테이션 레이어의 객체로서 **전체 정보에서 보여줄 정보를 제한해 이후의 수정이 불가하게 view로 던져주는 역할** 을 전담시켜야 할 겁니다. 물론 DTO에 대한 다양한 용례와 정의가 있습니다만, 우리가 지금 진행하고 있는 MVC 프로젝트에선 대개 그렇게 사용됩니다. 

따라서 DAO -> Entity -> DTO의 절차를 밟는 것이 맞습니다. 
사실 설계의 문제라서 다양한 의견들이 존재합니다. https://www.slipp.net/questions/93 이 링크를 참고해보시면 재밌을 거에요. 

Assembler나 Facade라는 것을 두기도 하는데요, 
https://buildplease.com/pages/repositories-dto/ 이것 읽어보심 좋겠고요, 
http://thierryroussel.free.fr/java/books/martinfowler/www.martinfowler.com/isa/distributedFacade.html 이것도 괜찮네요. 

> 제가 작성한 ItemDao 클래스에서 아래와 같이 하나의 아이템을 조회하는데 관계형 테이블로 연결된 항목들을 조회하기위해 여러번 쿼리를 요청합니다. 좋은 방식이 아니라고 생각이 듭니다. JOIN을 이용하면 쿼리 수를 줄일 수 있을까요? 아니면 어떤 방법이 있을까요?

*좋은 방식이 아니라고 생각이 든* 이유를 먼저 알아야할 것 같습니다. 
애플리케이션 레이어에서의 성능/클린코드 문제인지, 아니면 DBMS 상에서의 조회 퍼포먼스 문제인지요. 

쿼리 수를 줄인다고 무조건 더 좋은 성능이 나는 것도 아니고 `JOIN` 을 한다고 무조건 더 좋은 성능이 나는 것은 더더욱 아닙니다. 오히려 샤딩이 들어가있는 분산 데이터베이스 환경에서는 조인은 성능에 악영향을 미칠 수도 있습니다. 

먼저 해당 쿼리에 대해 `EXPLAIN` 쿼리 등을 사용해서 실행 비용이 어떻게 되는지, 어디에 드라이브가 걸리는지를 체크해야 할 겁니다(이 부분은 당연히 저보다 @honux77 님이 훨씬 더 잘 아십니다). 

https://jojoldu.tistory.com/173 이런 글이 있네요. 

JPA에 위임할 땐 쉽게 접근할 수 없는 튜닝 포인트지만 `JdbcTemplate` 을 이용하니 이런 튜닝 포인트를 잡아낼 수 있네요. 좋은데요? ㅋㅋㅋ 

어떻게 답변이 되었으면 좋겠네요.

2020-05-06 12:29 UTC, wooody92 commented on BE/sidedish11/HELP.md
> +# Getting Started
넵

2020-05-06 12:30 UTC, wooody92 commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/common/CommonUtils.java
> +public class CommonUtils {
StaticCommon? 음.. 역시 네이밍이 어렵네요.

2020-05-06 12:32 UTC, wooody92 commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/ApiDetailController.java
> +        return ResponseEntity.ok(itemDetailResponse);
넵. 컨트롤러에서 응답할 때 통일성을 주고싶어서 별개로 객체 만들었습니다.

2020-05-06 12:46 UTC, wooody92 commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/LoginController.java
> +        response.addCookie(cookie);
감사합니다! 
1. JWT 만료일 짧게 하고 Refresh Token을 추가로 발급하기
2. 로그아웃 시 블랙리스트 DB에 해당 토큰 추가하여 처리하기

2020-05-06 12:48 UTC, wooody92 commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/repository/CategoryDao.java
> +        jdbcTemplate = new JdbcTemplate(dataSource);
이번 프로젝트 때 적용해 봐야겠네요.

2020-05-06 12:50 UTC, wooody92 commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/service/LoginService.java
> +    @Transactional
정확한 동작원리 이해없이 남용 했네요. 반성합니다.. 공부하겠습니다.

2020-05-06 12:52 UTC, wooody92 commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/LoginController.java
> +        response.setHeader(AUTHORIZATION, jwt);
넵 토큰은 바디에..!

2020-05-06 12:58 UTC, wooody92 commented on BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/dto/ItemDetail.java
> +    public ItemDetail(Item item) {
키워드 감사합니다. 코드 작성하면서도 질문드린 것처럼 조금 찜찜한 부분이었어요.

2020-05-06 13:23 UTC, wooody92 commented
@wheejuni 
조금 추상적으로 질문드린것 같은데, 궁금했던점이 해소가 많이 됐습니다! 답변 감사합니다.
마지막 질문 같은 경우 좋은방식이 아니라고 생각한 이유는 하나의 요청에 날아가는 쿼리 갯수 때문입니다.
findById와 같이 하나의 요청에는 하나의 쿼리만 날아가는 것이 옳다고 생각했는데, 제가 작성한 코드의 경우 해당 테이블에 관계형으로 연결된 테이블의 정보를 가져오기위해 연쇄적으로 쿼리를 날려서 좋은 방식이 아니라고 생각했습니다. 이번 프로젝트에서는 팀원이 생겨 DAO 작성 시 같이 생각을 좀 더 해보려합니다. 감사합니다!

2020-05-10 14:47 UTC, closed without merging